from sqlalchemy import Column, Integer, VARCHAR, ForeignKey
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
import redis
import dotenv
import os

# MySQL db
db = SQLAlchemy()

# Redis (cache for Links data)
redis_client = redis.Redis(host="localhost", port=6379, decode_responses=True)


# user name <-> user password table
class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    username = Column(VARCHAR(20), unique=True, nullable=False)
    password = Column(VARCHAR(200), unique=False, nullable=False)

    rl = db.relationship("Links", backref="users", lazy=True, cascade="all, delete")

    def __repr__(self):
        return f"<User {self.username} with id {self.id}>"


# long link <-> short link table
class Links(db.Model):
    __tablename__ = "links"
    id = Column(Integer, unique=True, autoincrement=True, primary_key=True)
    original_url = Column(VARCHAR(250), nullable=False)
    shorter_url = Column(VARCHAR(50), nullable=True, unique=True)
    user_id = Column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )

    def __repr__(self):
        return f"<Original url: {self.original_url} || Shorter url: {self.shorter_url} || Generated by: {self.user_id}>"


# application initialization
def init_db(app):
    dotenv.load_dotenv()
    USR = os.getenv("USERNAME")
    PWD = os.getenv("PASSWORD")
    DB_NAME = os.getenv("DATABASE")

    # Application configuration
    CON_URI = f"mysql+pymysql://{USR}:{PWD}@localhost:3306/{DB_NAME}"
    app.config["SQLALCHEMY_DATABASE_URI"] = CON_URI
    app.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
        "pool_recycle": 28000,
        "pool_pre_ping": True,
    }

    db.init_app(app)

    with app.app_context():
        db.create_all()
