name: link_shortener

services:
  flask_application:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      redis_cache:
        condition: service_started
      mysql_db:
        condition: service_healthy

  redis_cache:
    image: "redis:8.0.3"
    ports:
      - "6379:6379"
    depends_on:
      mysql_db:
        condition: service_healthy

    
  mysql_db:
    image: "mysql:8.4.5"
    environment:
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 5s

volumes:
  db_data: